name: Analyze Code Quality

on: 
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
      SELISE_GITHUB_PAT:
        required: true

jobs:
  build:
    name: SonarQube Analysis
<<<<<<< HEAD
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  
        submodules: recursive
        token: ${{ secrets.SELISE_GITHUB_PAT }}

    - name: Set Environment Variables
      uses: ./.github/actions/setvars
      with:
        varFilePath: ./.github/variables/vars.env
    
    - name: Setup Node version 10
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        #node-version: 16.15

    - name: Install dependencies
      run: npm i
  
    - name: Test and coverage
      run: npm run test -- --coverage

    - name: Change abs paths to rel paths
      working-directory: ./coverage
      run: | 
        sed -i "s|/home/runner/work/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}/||g" lcov.info 
  
    - name: Set up JDK 17
      uses: actions/setup-java@v3.12.0
      with:
        distribution: 'microsoft'
        java-version: '17'
  
    - name: Cache SonarCloud packages
      uses: actions/cache@v3.3.1
      with:
        path: ~\sonar\cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ env.SONARQUBE_HOST }}

    # - name: SonarQube Quality Gate check
    #   uses: sonarsource/sonarqube-quality-gate-action@master
    #   # Force to fail step after specific time.
    #   timeout-minutes: 5
    #   env:
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #     SONAR_HOST_URL: ${{ env.SONARQUBE_HOST }}
=======
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.SELISE_GITHUB_PAT }}

      - name: Set Environment Variables
        uses: ./.github/actions/setvars
        with:
          varFilePath: ./.github/variables/vars.env

      - name: Setup Node version 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.13

      - name: Install dependencies
        run: npm i

      # - name: Test and coverage
      #   run: npm run test:coverage

      # - name: Change abs paths to rel paths
      #   working-directory: ./coverage
      #   run: | 
      #     sed -i "s|/home/runner/work/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}/||g" lcov.info 

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: "17"

      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: |
            ${{ runner.os }}-sonar

      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ env.SONARQUBE_HOST }}

      # - name: SonarQube Quality Gate check
      #   uses: sonarsource/sonarqube-quality-gate-action@master
      #   # Force to fail step after specific time.
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
<<<<<<< HEAD
      #     SONAR_HOST_URL: ${{ env.SONARQUBE_HOST }}
>>>>>>> f71df4e9e7617f195f77938742b3fa52f9785701
=======
      #     SONAR_HOST_URL: ${{ env.SONARQUBE_HOST }}
>>>>>>> 766308865e5fa2ff5ddfd0782ed7ded47edb956e
