name: Build (dev)

on:
  push:
    branches:
      - dev

jobs:
  initialization:
    runs-on: ubuntu-latest
    outputs:
      envvalue1: ${{ steps.setvar.outputs.envvar1 }}
    steps:
      - name: Set value
        id: setvar
        run: |
          echo envvar1="$RUN_SONARQUBE" >> $GITHUB_OUTPUT

  sonarqube-job:
    runs-on: ubuntu-latest
    needs: [initialization]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run SonarQube
        uses: SonarSource/sonarqube-scan-action@master
        with:
          sonarToken: ${{ secrets.SONAR_TOKEN_GLOBAL }}
          sonarHostUrl: https://code.selise.biz

  cd-job:
    if: ${{ github.event_name == 'push' }}
    uses: ./.github/workflows/3_web.yml
    with:
      CONTAINER_NAME: 'dev-$SERVICE_NAME-webclient'
      NAMESPACE: 'dev-$REPO_NAME'
      SERVICE_NAME: $SERVICE_NAME
      CI_BUILD: 'build-dev'
    secrets:
      SELISE_GITHUB_PAT: ${{ secrets.SELISE_GITHUB_PAT }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_AKS_BLOCKS_CREDENTIALS }}
      AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_BLOCKS_CONTAINER_REGISTRY }}
      ClUSTER_RESOURCE_GROUP: ${{ secrets.ClUSTER_AKS_BLOCKS_RESOURCE_GROUP }}
      CLUSTER_NAME: ${{ secrets.AKS_BLOCKS_DEV_CLUSTER }}
      ACR_RESOURCE_GROUP: ${{ secrets.ClUSTER_AKS_BLOCKS_RESOURCE_GROUP }}
    needs: [sonarqube-job]