name: Build (dev)

on:
  push:
    branches:
      - dev

jobs:
  initialization:
    runs-on: ubuntu-latest
    steps:
      - name: set value
        id: setvar
        run: |
          echo "Initialization step completed."

  sonarqube-job:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/2_sonar.yml
    secrets:
      SELISE_GITHUB_PAT: ${{ secrets.SELISE_GITHUB_PAT }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_GLOBAL }}
    needs: [initialization]

  cd-job:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    uses: ./.github/workflows/3_web.yml
    with:
      CONTAINER_NAME: 'dev-$SERVICE_NAME-webclient'
      NAMESPACE: 'dev-$REPO_NAME'
      SERVICE_NAME: $SERVICE_NAME
      CI_BUILD: 'build-dev'
    secrets:
      SELISE_GITHUB_PAT: ${{ secrets._PAT }}
      AZURE_CREDENTIALS: ${{ secrets.CREDENTIALS }}
      AZURE_CONTAINER_REGISTRY: ${{ secrets.REGISTRY }}
      ClUSTER_RESOURCE_GROUP: ${{ secrets._GROUP }}
      CLUSTER_NAME: ${{ secrets.AKS__CLUSTER }}
      ACR_RESOURCE_GROUP: ${{ secrets._GROUP }}
    needs: [sonarqube-job]
