name: Build (stg)

on:
  push:
    branches:
      - stg

env:
  RUN_UNIT_TEST: "false"
  RUN_SONARQUBE: "false"

jobs:
  initialization:
    runs-on: ubuntu-latest
    outputs:
      envvalue1: ${{ steps.setvar.outputs.envvar1 }}
      envvalue2: ${{ steps.setvar.outputs.envvar2 }}
    steps:
      - name: set value
        id: setvar
        run: |
          echo "::set-output name=envvar1::$RUN_UNIT_TEST" 
          echo "::set-output name=envvar2::$RUN_SONARQUBE"

  test-job:
    if: ${{ needs.initialization.outputs.envvalue1=='true' }}
    uses: ./.github/workflows/1_test.yml
    needs: [initialization]

  sonarqube-job:
    if: ${{ success() && needs.initialization.outputs.envvalue2=='true' }}
    uses: ./.github/workflows/2_sonar.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_GLOBAL }}
    needs: [test-job]

  cd-job:
    if: ${{ github.event_name == 'push' && (success() || (needs.initialization.outputs.envvalue1=='false' && needs.initialization.outputs.envvalue2=='false')) }}
    uses: ./.github/workflows/3_web.yml
    with:
      CONTAINER_NAME: "stg-blocks-$SERVICE_NAME"
      NAMESPACE: "stg-$REPO_NAME"
      SERVICE_NAME: $SERVICE_NAME
      CLUSTER_VALUES: "aks-blocks-stg"
    secrets:
      SELISE_GITHUB_PAT: ${{ secrets.SELISE_GITHUB_PAT }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_AKS_BLOCKS_CREDENTIALS }}
      AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_BLOCKS_CONTAINER_REGISTRY }}
      ClUSTER_RESOURCE_GROUP: ${{ secrets.ClUSTER_AKS_BLOCKS_RESOURCE_GROUP }}
      CLUSTER_NAME: ${{ secrets.AKS_BLOCKS_DEV_CLUSTER }}
      ACR_RESOURCE_GROUP: ${{ secrets.ClUSTER_AKS_BLOCKS_RESOURCE_GROUP }}
    #needs: [sonarqube-job]
    needs: [sonarqube-job]
